version: '3'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

  kafka:
    image: confluentinc/cp-kafka:6.0.0
    container_name: '${KAFKA_CONTAINER_NAME}'
    depends_on:
      - zookeeper
    ports:
      - '${KAFKA_INTERAL_BROKER_LISTENER_PORT}:${KAFKA_INTERAL_BROKER_LISTENER_PORT}'
      - '${KAFKA_OUTSIDE_BROKER_LISTENER_PORT}:${KAFKA_OUTSIDE_BROKER_LISTENER_PORT}'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:${KAFKA_INTERAL_BROKER_LISTENER_PORT},OUTSIDE://:${KAFKA_OUTSIDE_BROKER_LISTENER_PORT}
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://${KAFKA_CONTAINER_NAME}:${KAFKA_INTERAL_BROKER_LISTENER_PORT},OUTSIDE://host.docker.internal:${KAFKA_OUTSIDE_BROKER_LISTENER_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

  control-center:
    image: confluentinc/cp-enterprise-control-center:6.0.0
    hostname: control-center
    depends_on:
      - '${KAFKA_CONTAINER_NAME}'
    ports:
      - '${KAFKA_CONTROL_PORT}:${KAFKA_CONTROL_PORT}'
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: '${KAFKA_CONTAINER_NAME}:${KAFKA_INTERAL_BROKER_LISTENER_PORT}'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_CONNECT_CLUSTER: http://kafka-connect:8083
      PORT: '${KAFKA_CONTROL_PORT}'
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

  app:
    build: .
    container_name: gokafka
    depends_on:
      - '${KAFKA_CONTAINER_NAME}'
    volumes:
      - .:/go/src/
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
    environment:
      - KAFKA_PATH=${KAFKA_CONTAINER_NAME}
      - KAFKA_PORT=${KAFKA_INTERAL_BROKER_LISTENER_PORT}
